version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis: 
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/auth_service

  upload_video_service:
    build:
      context: ./upload_video_service
      dockerfile: Dockerfile
    container_name: upload_video_service
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis: 
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./upload_video_service:/upload_video_service

  mail_service:
    build:
      context: ./mail_service
      dockerfile: Dockerfile
    container_name: mail_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./mail_service/.env
    volumes:
      - ./mail_service:/mail_service

volumes:
  rabbit_data:
  redis_data:
