[project]
name = "mail-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faststream[cli,rabbit]>=0.6.0",
    "pydantic>=2.12.0",
    "pydantic-settings>=2.11.0",
    "redis>=6.4.0",
]
